spring:
  application:
    name: orchestrator

  datasource:
    url: ${STYXCD_DB_URL:jdbc:postgresql://localhost:5432/styxcd}
    username: ${STYXCD_DB_USERNAME:rincexwind}
    password: ${STYXCD_DB_PASSWORD:}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  address: 127.0.0.1
  port: 8080

styxcd:
  jenkins:
    base-url: http://jenkins.styxcd.com:8080
    job-name: external-input-orchestrator-test-json
    username: ${JENKINS_USERNAME}
    api-token: ${JENKINS_API_TOKEN}